export const recordingCopy = {
  header: {
    title: 'Recording',
    subtitle: '音声を録音する',
  },
  loading: {
    title: 'Preparing recorder',
    subtitle: 'マイクの許可を確認中…',
    accessibilityLabel: 'Preparing audio recorder',
  },
  permission: {
    title: 'Microphone Access',
    body: 'We need microphone access to record audio.',
    subtitle: '録音するにはマイクへのアクセスが必要です',
    grantLabel: 'Grant Microphone Permission',
    grantHint: 'Requests microphone access from the system',
    settingsLabel: 'Open Settings',
    settingsHint: 'Opens app settings so you can enable microphone access',
  },
  status: {
    ready: 'Ready',
    recording: 'Recording…',
    paused: 'Paused',
    complete: 'Recording complete',
  },
  menu: {
    recordSection: 'Record',
    playbackSection: 'Playback',
    saveSection: 'Save',
    statusSection: 'Status',
    start: 'Start Recording',
    startHint: 'Begins a new audio recording',
    pause: 'Pause',
    pauseHint: 'Pauses the current recording',
    resume: 'Resume',
    resumeHint: 'Continues the paused recording',
    stop: 'Stop',
    stopHint: 'Stops recording and keeps the clip',
    play: 'Play Recording',
    playHint: 'Plays the saved recording',
    save: 'Save to Gallery',
    saveHint: 'Saves the recording to your device library',
    saving: 'Saving…',
  },
  feedback: {
    nothingToPlay: 'Nothing to play',
    recordFirst: 'Please record something first.',
    saved: 'Recording saved to gallery.',
    saveFailed: 'Could not save recording.',
    playFailed: 'Could not play recording.',
    recordFailed: 'Could not start recording.',
    stopFailed: 'Could not stop recording.',
    setupFailed: 'Could not prepare the recorder.',
  },
  alerts: {
    libraryDeniedTitle: 'Media library access denied',
    libraryDeniedMessage: 'Enable media library access in settings to save recordings.',
    cancel: 'Cancel',
    openSettings: 'Open Settings',
  },
} as const;
